apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: ptp-event-consumer-service
  namespace: test
  labels:
    app: consumer
spec:
  ports:
    - name: sub-port
      port: 27017  
      targetPort: http
  selector:
    app: consumer
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
